version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mafinhobby_db
    restart: always
    environment:
      POSTGRES_USER: seckin_admin
      POSTGRES_PASSWORD: hobby_password_123
      POSTGRES_DB: mafinhobby_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: